### ISSUE TITLE
Survival friendly stage! (NOT AN ISSUE)

### ISSUE THREAD

**Issue by luigi052005** [Sk8kman/SongPlayer#5]
I created a survival-friendly stage design that can almost play every song.
[SurvivalStage.zip](https://github.com/Sk8kman/SongPlayer/files/13249346/SurvivalStage.zip)

**Comment by TahoeBennie** [comment]
There are 400 possible noteblock combinations, 25 noteblocks per instrument and 16 instruments. Your design here has 250 of those 400. However, Sk8kman and I have already created a design of our own that is able to use 359 of the 400 possible noteblocks. Not only that, but we were also able to configure it such that the 4 instruments that didn't have all 25 are the easiest to add/remove, and are the least used in most songs, making it able to play a vast majority of songs without switching out instruments, and it looks nice. It was never incorporated as part of the mod and honestly i'm not sure if it's planned or not, so here is that stage design:
[Survival Stage.zip](https://github.com/Sk8kman/SongPlayer/files/13257542/Survival.Stage.zip)

**Comment by Sk8kman** [comment]
Hey thanks for the stage design! I'd like to just use this to keep track of bugs and issues. But you can leave all feedback and criticism you may have in the "Discussions" tab if you'd like!
